import { generateKeypair, generateOotleAddress } from "@tari-project/ootle-wasm";
import { describe, expect, it } from "vitest";
import { componentAddressFromWalletAddress, deriveAccountComponentAddress, deriveComponentAddress } from "./componentAddress";

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe("deriveAccountComponentAddress", () => {
  // Golden vectors committed in tari-ootle's crates/ootle_sdk_core/fixtures/address_derive/*.json
  // (operation: derive_account_address), generated by the upstream Rust engine itself — same
  // vectors scripts/test-crypto.ts checks; kept here too so a regression fails fast in `npm test`
  // rather than only in the separate test:crypto script.
  const goldenVectors: [string, string][] = [
    ["f6f89e316e6ba5f05e5250ddd4a5d3ed39dcd038cf812cc6a154b6ec0951d25f", "component_26cf65a80010d961aa64950a5677fd9d3852adcf3618aa7fe171f6dda8b961ae"],
    ["44f53520926ec81fbd5a387845beb7df85a96a24ece18738bdcfa6a7822a176d", "component_23e5679a3e55e58e32318b94e258b73e72e3164b658f187fe5de833a861e2d45"],
    ["0707070707070707070707070707070707070707070707070707070707070707", "component_0f987d031de55aee41a7233426059b1c3506408832f3283eb2bdaed15a314021"],
  ];

  it.each(goldenVectors)("matches the golden vector for public key %s", (pubKeyHex, expected) => {
    expect(deriveAccountComponentAddress(hexToBytes(pubKeyHex))).toBe(expected);
  });

  it("is deterministic", () => {
    const pk = crypto.getRandomValues(new Uint8Array(32));
    expect(deriveAccountComponentAddress(pk)).toBe(deriveAccountComponentAddress(pk));
  });

  it("different public keys derive different addresses", () => {
    const a = deriveAccountComponentAddress(new Uint8Array(32).fill(1));
    const b = deriveAccountComponentAddress(new Uint8Array(32).fill(2));
    expect(a).not.toBe(b);
  });
});

describe("componentAddressFromWalletAddress", () => {
  // Round-trips a real bech32m "otl_..." address (built the same way the wallet itself builds one,
  // via generateOotleAddress) back through parseOotleAddress + deriveAccountComponentAddress, and
  // checks the result matches deriving straight from the owner public key -- i.e. that decoding a
  // recipient's wallet address gets you to the exact same component address they'd otherwise have
  // had to look up and paste in separately.
  const ownerPubKey = hexToBytes("f6f89e316e6ba5f05e5250ddd4a5d3ed39dcd038cf812cc6a154b6ec0951d25f");
  const viewPubKey = hexToBytes("44f53520926ec81fbd5a387845beb7df85a96a24ece18738bdcfa6a7822a176d");
  const ESMERALDA_NETWORK_BYTE = 38; // Network.Esmeralda (@tari-project/ootle)

  it("derives the same component address as deriving from the owner public key directly", () => {
    const walletAddress = generateOotleAddress(ownerPubKey, viewPubKey, ESMERALDA_NETWORK_BYTE);
    expect(walletAddress.startsWith("otl_")).toBe(true);
    expect(componentAddressFromWalletAddress(walletAddress)).toBe(deriveAccountComponentAddress(ownerPubKey));
  });

  it("ignores the view key -- only the owner key determines the component address", () => {
    // Needs a real point on the curve, not arbitrary bytes -- generateKeypair() gives us one.
    const otherViewPubKey = generateKeypair().public_key;
    const a = generateOotleAddress(ownerPubKey, viewPubKey, ESMERALDA_NETWORK_BYTE);
    const b = generateOotleAddress(ownerPubKey, otherViewPubKey, ESMERALDA_NETWORK_BYTE);
    expect(componentAddressFromWalletAddress(a)).toBe(componentAddressFromWalletAddress(b));
  });
});

describe("deriveComponentAddress input validation", () => {
  it("rejects a template address that isn't 32 bytes", () => {
    expect(() => deriveComponentAddress(new Uint8Array(31), new Uint8Array(32))).toThrow("templateAddress must be 32 bytes");
  });

  it("rejects a public key that isn't 32 bytes", () => {
    expect(() => deriveComponentAddress(new Uint8Array(32), new Uint8Array(33))).toThrow("publicKey must be 32 bytes");
  });
});
