import { entropyToMnemonic, generateMnemonic, mnemonicToEntropy, validateMnemonic } from "../src/lib/mnemonic";
import { deriveAccountKeys } from "../src/lib/derivation";
import { deriveAccountComponentAddress } from "../src/lib/componentAddress";

function assert(cond: boolean, msg: string) {
  if (!cond) throw new Error("FAIL: " + msg);
  console.log("ok  " + msg);
}

// Mnemonic round-trip
const mnemonic = generateMnemonic();
assert(mnemonic.split(" ").length === 24, "generateMnemonic produces 24 words");
assert(validateMnemonic(mnemonic), "generated mnemonic validates");
const entropy = mnemonicToEntropy(mnemonic);
assert(entropy.length === 32, "decoded entropy is 32 bytes");
const reencoded = entropyToMnemonic(entropy);
assert(reencoded === mnemonic, "entropy -> mnemonic round-trips exactly");

// Tampered checksum / word must fail
const words = mnemonic.split(" ");
words[0] = words[0] === "abandon" ? "ability" : "abandon";
const tampered = words.join(" ");
assert(!validateMnemonic(tampered), "tampering a word invalidates the mnemonic");

// Known-answer test: fixed entropy -> fixed mnemonic (all-zero entropy is BIP-39's own standard
// test vector, so this also cross-checks our checksum math against the spec, not just ourselves).
const zeroEntropy = new Uint8Array(32);
const zeroMnemonic = entropyToMnemonic(zeroEntropy);
console.log("zero-entropy mnemonic:", zeroMnemonic);
assert(
  zeroMnemonic ===
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
  "all-zero entropy matches the well-known BIP-39 test vector"
);

// Derivation determinism + distinctness
const seedA = mnemonicToEntropy(generateMnemonic());
const keys0a = deriveAccountKeys(seedA, 0);
const keys0b = deriveAccountKeys(seedA, 0);
assert(Buffer.from(keys0a.ownerSecret).equals(Buffer.from(keys0b.ownerSecret)), "same seed+index derives the same owner key twice");
assert(Buffer.from(keys0a.viewSecret).equals(Buffer.from(keys0b.viewSecret)), "same seed+index derives the same view key twice");

const keys1 = deriveAccountKeys(seedA, 1);
assert(!Buffer.from(keys0a.ownerSecret).equals(Buffer.from(keys1.ownerSecret)), "different account index derives a different owner key");
assert(!Buffer.from(keys0a.ownerSecret).equals(Buffer.from(keys0a.viewSecret)), "owner and view keys differ");

const seedB = mnemonicToEntropy(generateMnemonic());
const keys0c = deriveAccountKeys(seedB, 0);
assert(!Buffer.from(keys0a.ownerSecret).equals(Buffer.from(keys0c.ownerSecret)), "different seed derives a different owner key");

// Scalars must be reduced mod the group order (top bits of a 32-byte little-endian value can't
// all be set if it's < 2^252ish; a cheap sanity check that we didn't just return raw hash bytes).
const GROUP_ORDER = (1n << 252n) + 27742317777372353535851937790883648493n;
function leToBigInt(b: Uint8Array): bigint {
  let n = 0n;
  for (let i = b.length - 1; i >= 0; i--) n = (n << 8n) | BigInt(b[i]!);
  return n;
}
assert(leToBigInt(keys0a.ownerSecret) < GROUP_ORDER, "derived owner scalar is < group order");
assert(leToBigInt(keys0a.viewSecret) < GROUP_ORDER, "derived view scalar is < group order");

// Component-address derivation: golden vectors committed in tari-ootle's
// crates/ootle_sdk_core/fixtures/address_derive/*.json (operation: derive_account_address),
// generated by the upstream Rust engine itself. Byte-exact agreement here is the only thing
// standing between this wallet and sending funds to addresses nobody controls.
function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}
const goldenVectors: [string, string][] = [
  ["f6f89e316e6ba5f05e5250ddd4a5d3ed39dcd038cf812cc6a154b6ec0951d25f", "component_26cf65a80010d961aa64950a5677fd9d3852adcf3618aa7fe171f6dda8b961ae"],
  ["44f53520926ec81fbd5a387845beb7df85a96a24ece18738bdcfa6a7822a176d", "component_23e5679a3e55e58e32318b94e258b73e72e3164b658f187fe5de833a861e2d45"],
  ["0707070707070707070707070707070707070707070707070707070707070707", "component_0f987d031de55aee41a7233426059b1c3506408832f3283eb2bdaed15a314021"],
];
for (const [pubKeyHex, expected] of goldenVectors) {
  const got = deriveAccountComponentAddress(hexToBytes(pubKeyHex));
  assert(got === expected, `component address matches golden vector for pk ${pubKeyHex.slice(0, 8)}…`);
}

console.log("\nAll crypto core tests passed.");
